# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ACRTaskV0@0
  displayName: buildAcr
  inputs:
    azureSubscription: 'anshenoDev'
    azureContainerRegistry: 'ajacr4'
    connectionType: 'github'
    gitHubConnection: 'GitHub connection 2'
    repoUrl: '$(Build.Repository.Uri)'
    branch: 'test'
    dockerfileOrYaml: 'Dockerfile'
    imageNames: '$(Build.Repository.Name):$(Build.BuildId)'